import { test, expect, type Page } from '@playwright/test'
import { loadQuestions } from '../../server/questions.js'
const bank = loadQuestions('./questions')
async function join(page: Page, code: string) { await page.goto('/'); await page.getByLabel('Team code').fill(code); await page.getByRole('button', { name: 'Join', exact: true }).click(); await expect(page.getByRole('heading', { level: 1 })).toBeVisible() }
async function chooseCorrect(page: Page, subject: 'physics' | 'chemistry' | 'biology', index: number) { const q = bank[subject]['11–13'][index]; if (q.type === 'multiple-choice') await page.locator('.choice').nth(q.correctIndex).click(); else await page.getByLabel('Your answer').fill(q.type === 'text' ? q.acceptedAnswers[0] : String(q.numericAnswer)) }
test('real browser: admin, multiple sessions, subject progress, shared game and responsive layout', async ({ browser, page }, testInfo) => {
  const pageErrors: string[] = []; page.on('pageerror', e => pageErrors.push(e.message))
  await page.goto('/admin'); await page.getByLabel('Admin password').fill('browser-test-password'); await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.getByRole('button', { name: 'Add team', exact: true }).click();
  await page.getByLabel('Team name').fill('Photon Pigeons'); await page.getByLabel('Login code').fill('K7MP'); await page.getByRole('button', { name: 'Create team', exact: true }).click()
  await expect(page.getByRole('row', { name: /Photon Pigeons/ })).toBeVisible()
  await page.getByRole('button', { name: 'Add team', exact: true }).click();
  await page.getByLabel('Team name').fill('Older Owls'); await page.getByLabel('Age category').selectOption('17–18'); await page.getByLabel('Login code').fill('OWL7'); await page.getByRole('button', { name: 'Create team', exact: true }).click()
  await expect(page.getByRole('row', { name: /Older Owls/ })).toBeVisible()
  const contextA = await browser.newContext(), contextB = await browser.newContext(), contextC = await browser.newContext()
  const a = await contextA.newPage(), b = await contextB.newPage(), c = await contextC.newPage()
  for (const p of [a,b,c]) p.on('pageerror', e => pageErrors.push(e.message))
  await join(a, 'k7mp'); await join(b, 'K7MP'); await join(c, 'OWL7')
  await expect(a.getByRole('heading', { level: 1 })).toHaveText('Waiting for the start…')
  await expect(b.getByRole('heading', { level: 1 })).toHaveText('Waiting for the start…')
  await expect(a.getByRole('timer')).toHaveText('60:00')
  await expect(page.getByRole('timer')).toHaveText('60:00')
  await a.getByRole('link', { name: 'Game', exact: true }).click()
  await expect(a.getByRole('heading', { level: 1 })).toHaveText('Waiting for the start…')
  await expect(a.getByRole('region', { name: 'Fishing grounds' })).toHaveCount(0)
  await a.getByRole('link', { name: 'Questions', exact: true }).click()
  await a.screenshot({ path: testInfo.outputPath('waiting.png'), fullPage: true })
  await page.getByRole('button', { name: 'Start game', exact: true }).click()
  await expect(a.getByRole('heading', { level: 1 })).toHaveText(bank.physics['11–13'][0].prompt)
  await expect(a.getByRole('timer')).toHaveText(/59:[0-5][0-9]/)
  const booklet = a.getByRole('link', { name: /Booklet/ })
  await expect(booklet).toHaveAttribute('href', 'https://www.cygnusinternational.org/uploads/pdf/hbm6rSO9t5tdwQpUdwHjIbBjwTzUagQ3YB2ftRf3.pdf')
  await expect(booklet).toHaveAttribute('target', '_blank')
  // Intercept the external PDF so this check needs no internet or download.
  await contextA.route('https://www.cygnusinternational.org/**', route => route.fulfill({ contentType: 'text/html', body: '<p>Booklet</p>' }))
  const [bookletTab] = await Promise.all([contextA.waitForEvent('page'), booklet.click()])
  await bookletTab.waitForLoadState(); expect(bookletTab.url()).toContain('cygnusinternational.org'); await bookletTab.close()
  await a.getByRole('button', { name: 'ESS', exact: true }).click()
  await expect(a.getByRole('link', { name: /Booklet/ })).toHaveCount(0)
  await a.getByRole('button', { name: 'Physics', exact: true }).click()
  await expect(c.getByRole('heading', { level: 1 })).toHaveText(bank.physics['17–18'][0].prompt)
  await chooseCorrect(a, 'physics', 0); await a.getByRole('button', { name: 'Submit answer' }).click()
  await expect(a.getByRole('status')).toContainText('Correct · +10 Research')
  await expect(b.getByRole('heading', { level: 1 })).toHaveText(bank.physics['11–13'][1].prompt)
  await expect(b.locator('.research')).toContainText('10')
  await a.getByRole('button', { name: /^Chemistry/ }).click(); await b.getByRole('button', { name: /^Biology/ }).click()
  await chooseCorrect(a, 'chemistry', 0); await chooseCorrect(b, 'biology', 0)
  await Promise.all([a.getByRole('button', { name: 'Submit answer' }).click(), b.getByRole('button', { name: 'Submit answer' }).click()])
  await expect(a.locator('.research')).toContainText('30'); await expect(b.locator('.research')).toContainText('30')
  await a.getByRole('button', { name: /^Physics/ }).click(); await expect(a.getByRole('heading', { level: 1 })).toHaveText(bank.physics['11–13'][1].prompt)
  await a.reload(); await expect(a.locator('.team-heading')).toContainText('Photon Pigeons')
  await a.screenshot({ path: testInfo.outputPath('questions-desktop.png'), fullPage: true })
  await a.getByRole('link', { name: 'Game', exact: true }).click(); await c.getByRole('link', { name: 'Game', exact: true }).click()
  // Two teams: four grounds. Orders are free and visible to every team at once.
  await expect(a.locator('.ground')).toHaveCount(4)
  await expect(a.getByRole('button', { name: /^Ground A: 8 of 12 fish, growth \+3/ })).toBeVisible()
  await a.getByRole('button', { name: /^Ground A:.*Send boat 1 here/ }).click()
  await expect(a.getByRole('button', { name: /^Boat 1/ })).toContainText('Travels to A at the next resolution')
  await a.getByRole('button', { name: /^Boat 2/ }).click()
  await a.getByRole('button', { name: /^Ground B:.*Send boat 2 here/ }).click()
  await expect(a.getByRole('button', { name: /^Ground B:.*Boat 2 is heading here/ })).toBeVisible()
  await expect(c.getByRole('button', { name: /^Ground A:/ }).locator('.chip.arriving')).toHaveText('→PP1')
  await expect(a.locator('.research')).toContainText('30')
  await a.getByRole('button', { name: 'Take: Fish at 5 different grounds' }).click()
  await expect(a.locator('.contracts li.active')).toContainText('0/5')
  await expect(c.locator('.contracts li', { hasText: 'Fish at 5 different grounds' }).locator('.chip')).toHaveText('PP')
  // Resolution 1: both boats travel. Resolution 2: both fish and pay.
  await a.request.post('/__test/rewind/180000')
  await expect(a.locator('.last-resolution')).toContainText('Boat 1 travelled to A.')
  await expect(a.getByRole('button', { name: /^Boat 1/ })).toContainText('Fishing at A')
  await a.request.post('/__test/rewind/180000')
  await expect(a.locator('.last-resolution')).toContainText('Boat 2 caught 2 fish at B.')
  await expect(a.locator('.own-score')).toContainText('Score 4')
  await expect(a.locator('.research')).toContainText('20')
  await expect(a.locator('.contracts li.active')).toContainText('2/5')
  await expect(a.locator('.ground-results').getByRole('row', { name: /^A / })).toHaveText(/A\s*11\s*−2\s*\+3\s*12/)
  await a.screenshot({ path: testInfo.outputPath('game-desktop.png'), fullPage: true })
  await c.getByRole('link', { name: 'Standings', exact: true }).click()
  await expect(c.getByRole('region', { name: 'Scores' }).getByRole('row', { name: /Photon Pigeons/ }).getByRole('cell')).toHaveText('4')
  await c.getByRole('link', { name: 'Game', exact: true }).click()
  await expect(c.getByRole('button', { name: /^Ground A: 12 of 12 fish, growth \+0; 1 boats fishing next/ })).toBeVisible()
  await a.getByRole('button', { name: 'Leave boat 2 idle', exact: true }).click()
  await expect(a.getByRole('button', { name: /^Boat 2/ })).toContainText('Idle at B')
  await a.getByRole('button', { name: 'Abandon', exact: true }).click()
  await expect(a.getByRole('alertdialog')).toContainText('Its progress (2/5) will be lost.')
  await a.getByRole('alertdialog').getByRole('button', { name: 'Abandon', exact: true }).click()
  await expect(a.locator('.contracts li.active')).toHaveCount(0)
  await expect(c.locator('.contracts li', { hasText: 'Fish at 5 different grounds' }).locator('.chip')).toHaveCount(0)
  await a.getByRole('link', { name: 'Questions', exact: true }).click(); await expect(a.getByRole('heading', { level: 1 })).toHaveText(bank.physics['11–13'][1].prompt)
  await a.setViewportSize({ width: 390, height: 844 }); await a.screenshot({ path: testInfo.outputPath('questions-mobile.png'), fullPage: true })
  expect(await a.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await a.getByRole('button', { name: 'Skip question', exact: true }).scrollIntoViewIfNeeded(); expect(await a.locator('.research').evaluate(el => el.getBoundingClientRect().top)).toBeGreaterThanOrEqual(0); await a.getByRole('button', { name: 'Skip question', exact: true }).click(); await a.getByRole('button', { name: 'Yes, skip' }).click(); await expect(a.getByText('4 team skips left')).toBeVisible()
  await a.getByRole('link', { name: 'Game', exact: true }).click(); await a.screenshot({ path: testInfo.outputPath('game-mobile.png'), fullPage: true }); expect(await a.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await expect(page.getByRole('row', { name: /Photon Pigeons/ }).getByRole('cell').nth(2)).toHaveText('20')
  await expect(page.getByRole('row', { name: /Photon Pigeons/ }).getByRole('cell').nth(3)).toHaveText('4')
  await page.screenshot({ path: testInfo.outputPath('admin.png'), fullPage: true })
  await a.getByRole('link', { name: 'Standings', exact: true }).click()
  await expect(a.getByRole('heading', { name: 'Standings', exact: true })).toBeVisible()
  await expect(a.getByRole('region', { name: 'Scores' }).getByRole('row', { name: /Photon Pigeons/ }).getByRole('cell')).toHaveText('4')
  await a.screenshot({ path: testInfo.outputPath('standings-mobile.png'), fullPage: true })
  expect(await a.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  // The game resolutions above moved the shared start six minutes back.
  await a.reload(); await expect(a.getByRole('timer')).toHaveText(/5[34]:[0-5][0-9]/)
  await a.getByRole('link', { name: 'Questions', exact: true }).click()
  await contextA.route('**/api/team/state', async route => {
    const response = await route.fetch(), body = await response.json()
    body.standings.frozenAt = Date.now()
    await route.fulfill({ response, json: body })
  })
  await a.getByRole('link', { name: 'Standings', exact: true }).click()
  await expect(a.getByText('Frozen for the final 5 minutes.', { exact: true })).toBeVisible()
  await a.reload()
  await expect(a.getByText('Frozen for the final 5 minutes.', { exact: true })).toBeVisible()
  await contextA.unroute('**/api/team/state')
  // An authoritative expiry response should immediately replace either view.
  await contextA.route('**/api/**', async route => {
    const path = new URL(route.request().url()).pathname
    if (!['/api/competition', '/api/team/state'].includes(path)) return route.continue()
    const response = await route.fetch(), body = await response.json()
    const clock = path === '/api/competition' ? body : body.competition
    clock.status = 'finished'; clock.endsAt = clock.serverNow - 1
    await route.fulfill({ response, json: body })
  })
  await expect(a.getByRole('heading', { level: 1 })).toHaveText('Competition over.')
  await expect(a.getByRole('region', { name: 'Scores' })).toHaveCount(0)
  await expect(a.getByRole('timer')).toHaveText('00:00')
  await expect(a.getByRole('button', { name: 'Submit answer' })).toHaveCount(0)
  await a.getByRole('link', { name: 'Game', exact: true }).click()
  await expect(a.getByRole('region', { name: 'Fishing grounds' })).toHaveCount(0)
  await expect(a.locator('.ground')).toHaveCount(0)
  await a.getByRole('link', { name: 'Standings', exact: true }).click()
  await expect(a.getByRole('heading', { level: 1 })).toHaveText('Competition over.')
  await expect(a.getByRole('region', { name: 'Scores' })).toHaveCount(0)
  expect(pageErrors).toEqual([])
  await contextA.close(); await contextB.close(); await contextC.close()
})
test('invalid code and offline failures are understandable', async ({ page }) => {
  await page.goto('/'); await page.getByLabel('Team code').fill('ZZZZ'); await page.getByRole('button', { name: 'Join', exact: true }).click(); await expect(page.getByRole('alert')).toContainText('That code was not found')
  await page.route('**/api/team/login', route => route.abort()); await page.getByRole('button', { name: 'Join', exact: true }).click(); await expect(page.getByRole('alert')).toContainText('Cannot reach the server')
})

test('Czech UI and grading share progress without changing drafts or attempts', async ({ browser, page }, testInfo) => {
  const headers = { 'X-Competition-Client': '1' }
  await page.request.post('/api/admin/login', { headers, data: { password: 'browser-test-password' } })
  await page.request.post('/api/admin/teams', { headers, data: { name: 'Czech team', age: '11–13', code: 'CZ11' } })
  const competition = await (await page.request.get('/api/competition')).json()
  if (competition.status === 'waiting') await page.request.post('/api/admin/start', { headers, data: {} })
  const otherContext = await browser.newContext()
  const other = await otherContext.newPage()
  await join(other, 'CZ11')
  await page.goto('/')
  await page.getByLabel('Language / Jazyk').selectOption('cs')
  await expect(page.locator('html')).toHaveAttribute('lang', 'cs')
  await page.getByLabel('Kód týmu').fill('CZ11')
  await page.getByRole('button', { name: 'Připojit se', exact: true }).click()
  const first = bank.physics['11–13'][0]
  expect(first.type).toBe('multiple-choice')
  if (first.type !== 'multiple-choice') throw new Error('Expected MC fixture')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText(first.cs.prompt)
  await page.locator('.choice').nth(first.correctIndex).click()
  await page.getByLabel('Language / Jazyk').selectOption('en')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText(first.prompt)
  await expect(page.getByRole('radio').nth(first.correctIndex)).toBeChecked()
  await page.getByLabel('Language / Jazyk').selectOption('cs')
  await expect(page.getByRole('radio').nth(first.correctIndex)).toBeChecked()
  const unchanged = await (await page.request.get('/api/team/state')).json()
  expect(unchanged.progress.physics.attempts).toBe(0)
  expect(unchanged.team.research).toBe(0)
  await page.getByRole('button', { name: 'Odeslat odpověď' }).click()
  await expect(page.getByRole('status')).toContainText('Správně · +10 Výzkum')
  await expect(other.getByRole('heading', { level: 1 })).toHaveText(bank.physics['11–13'][1].prompt)
  await expect(other.getByLabel('Language / Jazyk')).toHaveValue('en')
  await expect(other.locator('.research')).toContainText('10 Research')
  await page.getByRole('button', { name: 'Biologie', exact: true }).click()
  const bio = bank.biology['11–13'][0]
  if (bio.type !== 'multiple-choice') throw new Error('Expected MC fixture')
  await page.locator('.choice').nth(bio.correctIndex).click()
  await page.getByRole('button', { name: 'Odeslat odpověď' }).click()
  await page.getByLabel('Vaše odpověď').fill('60,0')
  await page.getByLabel('Language / Jazyk').selectOption('en')
  await expect(page.getByLabel('Your answer')).toHaveValue('60,0')
  await page.getByLabel('Language / Jazyk').selectOption('cs')
  await page.getByRole('button', { name: 'Odeslat odpověď' }).click()
  await expect(page.getByRole('status')).toContainText('Správně · +10 Výzkum')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText(bank.biology['11–13'][2].cs.prompt)
  await chooseCorrect(other, 'physics', 1)
  await other.getByRole('button', { name: 'Submit answer' }).click()
  await page.getByRole('button', { name: 'Fyzika', exact: true }).click()
  await expect(page.getByRole('heading', { level: 1 })).toHaveText(bank.physics['11–13'][2].cs.prompt)
  await page.getByLabel('Vaše odpověď').fill('5,0')
  await page.getByRole('button', { name: 'Odeslat odpověď' }).click()
  await expect(page.getByRole('status')).toContainText('Správně · +10 Výzkum')
  await page.reload()
  await expect(page.getByLabel('Language / Jazyk')).toHaveValue('cs')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText(bank.physics['11–13'][3].cs.prompt)
  await page.getByLabel('Vaše odpověď').fill('  dolů  ')
  await page.getByRole('button', { name: 'Odeslat odpověď' }).click()
  await expect(page.locator('.research')).toContainText('60 Výzkum')
  await expect(other.locator('.research')).toContainText('60 Research')
  // Czech scientific text and code output both work, even after switching UI language.
  const csTrack = bank['computer-science']['11–13']
  const textIndex = csTrack.findIndex(q => q.id === 'computer-science-11-09')
  expect(textIndex).toBeGreaterThanOrEqual(0)
  for (const q of csTrack.slice(0, textIndex)) {
    const answer = q.type === 'multiple-choice' ? String(q.correctIndex) : q.type === 'numerical' ? String(q.numericAnswer) : q.acceptedAnswers[0]
    const response = await page.request.post('/api/team/answer', { headers, data: { subject: 'computer-science', questionId: q.id, answer } })
    expect(response.ok()).toBe(true)
  }
  await page.getByRole('button', { name: 'Informatika', exact: true }).click()
  await expect(page.getByRole('heading', { level: 1 })).toHaveText(csTrack[textIndex].cs.prompt)
  await page.getByLabel('Vaše odpověď').fill('  ne  ')
  await page.getByLabel('Language / Jazyk').selectOption('en')
  await expect(page.getByLabel('Your answer')).toHaveValue('  ne  ')
  await page.getByRole('button', { name: 'Submit answer' }).click()
  await expect(page.getByRole('status')).toContainText('Correct · +10 Research')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText(csTrack[textIndex + 1].prompt)
  await page.getByLabel('Language / Jazyk').selectOption('cs')
  await expect(other.locator('.research')).toContainText('160 Research')
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('czech-questions-mobile.png'), fullPage: true })
  await page.getByRole('link', { name: 'Hra', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Loviště' })).toBeVisible()
  await expect(page.getByRole('button', { name: /^Loviště A: .* z 12 ryb, přírůstek/ })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Zakázky' })).toBeVisible()
  await page.getByRole('link', { name: 'Pořadí', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Pořadí' })).toBeVisible()
  await page.goto('/admin')
  await expect(page.getByRole('heading', { name: 'Týmy', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Přidat tým' })).toBeVisible()
  await otherContext.close()
})
