import { test, expect, type Page } from '@playwright/test'
import { loadQuestions } from '../../server/questions.js'
const bank = loadQuestions('./questions')
async function join(page: Page, code: string) { await page.goto('/'); await page.getByLabel('Team code').fill(code); await page.getByRole('button', { name: 'Join', exact: true }).click(); await expect(page.getByRole('heading', { level: 1 })).toBeVisible() }
async function chooseCorrect(page: Page, subject: 'physics' | 'chemistry' | 'biology', index: number) { const q = bank[subject]['11–13'][index]; if (q.type === 'multiple-choice') await page.locator('.choice').nth(q.correctIndex).click(); else await page.getByLabel('Your answer').fill(q.type === 'text' ? q.acceptedAnswers[0] : String(q.numericAnswer)) }
test('real browser: admin, multiple sessions, subject progress, shared game and responsive layout', async ({ browser, page }, testInfo) => {
  const pageErrors: string[] = []; page.on('pageerror', e => pageErrors.push(e.message))
  await page.goto('/admin'); await page.getByLabel('Admin password').fill('browser-test-password'); await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.getByRole('button', { name: 'Add team', exact: true }).click();
  await page.getByLabel('Team name').fill('Photon Pigeons'); await page.getByLabel('Login code').fill('K7MP'); await page.getByRole('button', { name: 'Create team', exact: true }).click()
  await expect(page.getByRole('row', { name: /Photon Pigeons/ })).toBeVisible()
  await page.getByRole('button', { name: 'Add team', exact: true }).click();
  await page.getByLabel('Team name').fill('Older Owls'); await page.getByLabel('Age category').selectOption('17–18'); await page.getByLabel('Login code').fill('OWL7'); await page.getByRole('button', { name: 'Create team', exact: true }).click()
  await expect(page.getByRole('row', { name: /Older Owls/ })).toBeVisible()
  const contextA = await browser.newContext(), contextB = await browser.newContext(), contextC = await browser.newContext()
  const a = await contextA.newPage(), b = await contextB.newPage(), c = await contextC.newPage()
  for (const p of [a,b,c]) p.on('pageerror', e => pageErrors.push(e.message))
  await join(a, 'k7mp'); await join(b, 'K7MP'); await join(c, 'OWL7')
  await expect(a.getByRole('heading', { level: 1 })).toHaveText('Waiting for the start…')
  await expect(b.getByRole('heading', { level: 1 })).toHaveText('Waiting for the start…')
  await expect(a.getByRole('timer')).toHaveText('45:00')
  await expect(page.getByRole('timer')).toHaveText('45:00')
  await a.getByRole('link', { name: 'Game', exact: true }).click()
  await expect(a.getByRole('heading', { level: 1 })).toHaveText('Waiting for the start…')
  await expect(a.getByLabel('Shared game board')).toHaveCount(0)
  await a.getByRole('link', { name: 'Questions', exact: true }).click()
  await a.screenshot({ path: testInfo.outputPath('waiting.png'), fullPage: true })
  await page.getByRole('button', { name: 'Start game', exact: true }).click()
  await expect(a.getByRole('heading', { level: 1 })).toHaveText(bank.physics['11–13'][0].prompt)
  await expect(a.getByRole('timer')).toHaveText(/44:[0-5][0-9]/)
  const booklet = a.getByRole('link', { name: /Booklet/ })
  await expect(booklet).toHaveAttribute('href', 'https://www.cygnusinternational.org/uploads/pdf/hbm6rSO9t5tdwQpUdwHjIbBjwTzUagQ3YB2ftRf3.pdf')
  await expect(booklet).toHaveAttribute('target', '_blank')
  // Intercept the external PDF so this check needs no internet or download.
  await contextA.route('https://www.cygnusinternational.org/**', route => route.fulfill({ contentType: 'text/html', body: '<p>Booklet</p>' }))
  const [bookletTab] = await Promise.all([contextA.waitForEvent('page'), booklet.click()])
  await bookletTab.waitForLoadState(); expect(bookletTab.url()).toContain('cygnusinternational.org'); await bookletTab.close()
  await a.getByRole('button', { name: 'ESS', exact: true }).click()
  await expect(a.getByRole('link', { name: /Booklet/ })).toHaveCount(0)
  await a.getByRole('button', { name: 'Physics', exact: true }).click()
  await expect(c.getByRole('heading', { level: 1 })).toHaveText(bank.physics['17–18'][0].prompt)
  await chooseCorrect(a, 'physics', 0); await a.getByRole('button', { name: 'Submit answer' }).click()
  await expect(a.getByRole('status')).toContainText('Correct · +10 Research')
  await expect(b.getByRole('heading', { level: 1 })).toHaveText(bank.physics['11–13'][1].prompt)
  await expect(b.locator('.research')).toContainText('10')
  await a.getByRole('button', { name: /^Chemistry/ }).click(); await b.getByRole('button', { name: /^Biology/ }).click()
  await chooseCorrect(a, 'chemistry', 0); await chooseCorrect(b, 'biology', 0)
  await Promise.all([a.getByRole('button', { name: 'Submit answer' }).click(), b.getByRole('button', { name: 'Submit answer' }).click()])
  await expect(a.locator('.research')).toContainText('30'); await expect(b.locator('.research')).toContainText('30')
  await a.getByRole('button', { name: /^Physics/ }).click(); await expect(a.getByRole('heading', { level: 1 })).toHaveText(bank.physics['11–13'][1].prompt)
  await a.reload(); await expect(a.locator('.team-heading')).toContainText('Photon Pigeons')
  await a.screenshot({ path: testInfo.outputPath('questions-desktop.png'), fullPage: true })
  await a.getByRole('link', { name: 'Game', exact: true }).click(); await c.getByRole('link', { name: 'Game', exact: true }).click()
  await a.getByRole('button', { name: /Column 2, row 1.*move here/ }).click()
  await expect(a.locator('.research')).toContainText('29')
  await expect(c.getByRole('button', { name: /Column 2, row 1:.*Photon Pigeons/ })).toBeVisible()
  await expect(a.getByText('3 left here', { exact: true })).toBeVisible()
  await a.getByRole('button', { name: 'Mine 1 diamond', exact: true }).click()
  await expect(a.locator('.diamond-total')).toHaveText('1 diamond')
  await expect(a.getByText('2 left here', { exact: true })).toBeVisible()
  await expect(a.locator('.research')).toContainText('29')
  await c.getByRole('link', { name: 'Standings', exact: true }).click()
  await expect(c.getByRole('region', { name: 'Diamond scores' }).getByRole('row', { name: /Photon Pigeons/ }).getByRole('cell')).toHaveText('1')
  await c.getByRole('link', { name: 'Game', exact: true }).click()
  await expect(c.getByRole('button', { name: /Column 2, row 1:.*2 diamonds/ })).toBeVisible()
  await a.getByRole('button', { name: 'Mine 1 diamond', exact: true }).click()
  await expect(a.locator('.diamond-total')).toHaveText('2 diamonds')
  await a.getByRole('button', { name: 'Mine 1 diamond', exact: true }).click()
  await expect(a.locator('.diamond-total')).toHaveText('3 diamonds')
  await expect(a.getByRole('button', { name: 'Mine 1 diamond', exact: true })).toBeDisabled()
  await expect(c.getByText('0 left here', { exact: true })).toBeVisible()
  await a.getByRole('link', { name: 'Questions', exact: true }).click(); await expect(a.getByRole('heading', { level: 1 })).toHaveText(bank.physics['11–13'][1].prompt)
  await a.setViewportSize({ width: 390, height: 844 }); await a.screenshot({ path: testInfo.outputPath('questions-mobile.png'), fullPage: true })
  expect(await a.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await a.getByRole('button', { name: 'Skip question', exact: true }).scrollIntoViewIfNeeded(); expect(await a.locator('.research').evaluate(el => el.getBoundingClientRect().top)).toBeGreaterThanOrEqual(0); await a.getByRole('button', { name: 'Skip question', exact: true }).click(); await a.getByRole('button', { name: 'Yes, skip' }).click(); await expect(a.getByText('2 team skips left')).toBeVisible()
  await a.getByRole('link', { name: 'Game', exact: true }).click(); await a.screenshot({ path: testInfo.outputPath('game-mobile.png'), fullPage: true }); expect(await a.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await expect(page.getByRole('row', { name: /Photon Pigeons/ }).getByRole('cell').nth(2)).toHaveText('29')
  await expect(page.getByRole('row', { name: /Photon Pigeons/ }).getByRole('cell').nth(3)).toHaveText('3')
  await page.screenshot({ path: testInfo.outputPath('admin.png'), fullPage: true })
  await a.getByRole('link', { name: 'Standings', exact: true }).click()
  await expect(a.getByRole('heading', { name: 'Standings', exact: true })).toBeVisible()
  await expect(a.getByRole('region', { name: 'Diamond scores' }).getByRole('row', { name: /Photon Pigeons/ }).getByRole('cell')).toHaveText('3')
  await a.screenshot({ path: testInfo.outputPath('standings-mobile.png'), fullPage: true })
  expect(await a.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await a.reload(); await expect(a.getByRole('timer')).toHaveText(/44:[0-5][0-9]/)
  await a.getByRole('link', { name: 'Questions', exact: true }).click()
  await contextA.route('**/api/team/state', async route => {
    const response = await route.fetch(), body = await response.json()
    body.standings.frozenAt = Date.now()
    await route.fulfill({ response, json: body })
  })
  await a.getByRole('link', { name: 'Standings', exact: true }).click()
  await expect(a.getByText('Frozen for the final 5 minutes.', { exact: true })).toBeVisible()
  await a.reload()
  await expect(a.getByText('Frozen for the final 5 minutes.', { exact: true })).toBeVisible()
  await contextA.unroute('**/api/team/state')
  // An authoritative expiry response should immediately replace either view.
  await contextA.route('**/api/**', async route => {
    const path = new URL(route.request().url()).pathname
    if (!['/api/competition', '/api/team/state'].includes(path)) return route.continue()
    const response = await route.fetch(), body = await response.json()
    const clock = path === '/api/competition' ? body : body.competition
    clock.status = 'finished'; clock.endsAt = clock.serverNow - 1
    await route.fulfill({ response, json: body })
  })
  await expect(a.getByRole('heading', { level: 1 })).toHaveText('Competition over.')
  await expect(a.getByRole('region', { name: 'Diamond scores' })).toHaveCount(0)
  await expect(a.getByRole('timer')).toHaveText('00:00')
  await expect(a.getByRole('button', { name: 'Submit answer' })).toHaveCount(0)
  await a.getByRole('link', { name: 'Game', exact: true }).click()
  await expect(a.getByLabel('Shared game board')).toHaveCount(0)
  await expect(a.getByRole('button', { name: 'Mine 1 diamond', exact: true })).toHaveCount(0)
  await a.getByRole('link', { name: 'Standings', exact: true }).click()
  await expect(a.getByRole('heading', { level: 1 })).toHaveText('Competition over.')
  await expect(a.getByRole('region', { name: 'Diamond scores' })).toHaveCount(0)
  expect(pageErrors).toEqual([])
  await contextA.close(); await contextB.close(); await contextC.close()
})
test('invalid code and offline failures are understandable', async ({ page }) => {
  await page.goto('/'); await page.getByLabel('Team code').fill('ZZZZ'); await page.getByRole('button', { name: 'Join', exact: true }).click(); await expect(page.getByRole('alert')).toContainText('That code was not found')
  await page.route('**/api/team/login', route => route.abort()); await page.getByRole('button', { name: 'Join', exact: true }).click(); await expect(page.getByRole('alert')).toContainText('Cannot reach the server')
})
