import { test, expect, type Page } from '@playwright/test'
import { loadQuestions } from '../../server/questions.js'
const bank = loadQuestions('./questions')
async function join(page: Page, code: string) { await page.goto('/'); await page.getByLabel('Team code').fill(code); await page.getByRole('button', { name: 'Join', exact: true }).click(); await expect(page.getByRole('heading', { level: 1 })).toBeVisible() }
async function chooseCorrect(page: Page, subject: 'physics' | 'chemistry' | 'biology', index: number) { const q = bank[subject]['11–13'][index]; if (q.type === 'multiple-choice') await page.locator('.choice').nth(q.correctIndex).click(); else await page.getByLabel('Your answer').fill(q.type === 'text' ? q.acceptedAnswers[0] : String(q.numericAnswer)) }
test('real browser: admin, multiple sessions, subject progress, shared game and responsive layout', async ({ browser, page }, testInfo) => {
  const pageErrors: string[] = []; page.on('pageerror', e => pageErrors.push(e.message))
  await page.goto('/admin'); await page.getByLabel('Admin password').fill('browser-test-password'); await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.getByRole('button', { name: 'Add team', exact: true }).click();
  await page.getByLabel('Team name').fill('Photon Pigeons'); await page.getByLabel('Login code').fill('K7MP'); await page.getByRole('button', { name: 'Create team', exact: true }).click()
  await expect(page.getByRole('row', { name: /Photon Pigeons/ })).toBeVisible()
  await page.getByRole('button', { name: 'Add team', exact: true }).click();
  await page.getByLabel('Team name').fill('Older Owls'); await page.getByLabel('Age category').selectOption('17–18'); await page.getByLabel('Login code').fill('OWL7'); await page.getByRole('button', { name: 'Create team', exact: true }).click()
  await expect(page.getByRole('row', { name: /Older Owls/ })).toBeVisible()
  const contextA = await browser.newContext(), contextB = await browser.newContext(), contextC = await browser.newContext()
  const a = await contextA.newPage(), b = await contextB.newPage(), c = await contextC.newPage()
  for (const p of [a,b,c]) p.on('pageerror', e => pageErrors.push(e.message))
  await join(a, 'k7mp'); await join(b, 'K7MP'); await join(c, 'OWL7')
  await expect(a.getByRole('heading', { level: 1 })).toHaveText('Waiting for the start…')
  await expect(b.getByRole('heading', { level: 1 })).toHaveText('Waiting for the start…')
  await expect(a.getByRole('timer')).toHaveText('45:00')
  await expect(page.getByRole('timer')).toHaveText('45:00')
  await a.getByRole('link', { name: 'Game', exact: true }).click()
  await expect(a.getByRole('heading', { level: 1 })).toHaveText('Waiting for the start…')
  await expect(a.getByRole('region', { name: 'Fishing grounds' })).toHaveCount(0)
  await a.getByRole('link', { name: 'Questions', exact: true }).click()
  await a.screenshot({ path: testInfo.outputPath('waiting.png'), fullPage: true })
  await page.getByRole('button', { name: 'Start game', exact: true }).click()
  await expect(a.getByRole('heading', { level: 1 })).toHaveText(bank.physics['11–13'][0].prompt)
  await expect(a.getByRole('timer')).toHaveText(/44:[0-5][0-9]/)
  const booklet = a.getByRole('link', { name: /Booklet/ })
  await expect(booklet).toHaveAttribute('href', 'https://www.cygnusinternational.org/uploads/pdf/hbm6rSO9t5tdwQpUdwHjIbBjwTzUagQ3YB2ftRf3.pdf')
  await expect(booklet).toHaveAttribute('target', '_blank')
  // Intercept the external PDF so this check needs no internet or download.
  await contextA.route('https://www.cygnusinternational.org/**', route => route.fulfill({ contentType: 'text/html', body: '<p>Booklet</p>' }))
  const [bookletTab] = await Promise.all([contextA.waitForEvent('page'), booklet.click()])
  await bookletTab.waitForLoadState(); expect(bookletTab.url()).toContain('cygnusinternational.org'); await bookletTab.close()
  await a.getByRole('button', { name: 'ESS', exact: true }).click()
  await expect(a.getByRole('link', { name: /Booklet/ })).toHaveCount(0)
  await a.getByRole('button', { name: 'Physics', exact: true }).click()
  await expect(c.getByRole('heading', { level: 1 })).toHaveText(bank.physics['17–18'][0].prompt)
  await chooseCorrect(a, 'physics', 0); await a.getByRole('button', { name: 'Submit answer' }).click()
  await expect(a.getByRole('status')).toContainText('Correct · +10 Research')
  await expect(b.getByRole('heading', { level: 1 })).toHaveText(bank.physics['11–13'][1].prompt)
  await expect(b.locator('.research')).toContainText('10')
  await a.getByRole('button', { name: /^Chemistry/ }).click(); await b.getByRole('button', { name: /^Biology/ }).click()
  await chooseCorrect(a, 'chemistry', 0); await chooseCorrect(b, 'biology', 0)
  await Promise.all([a.getByRole('button', { name: 'Submit answer' }).click(), b.getByRole('button', { name: 'Submit answer' }).click()])
  await expect(a.locator('.research')).toContainText('30'); await expect(b.locator('.research')).toContainText('30')
  await a.getByRole('button', { name: /^Physics/ }).click(); await expect(a.getByRole('heading', { level: 1 })).toHaveText(bank.physics['11–13'][1].prompt)
  await a.reload(); await expect(a.locator('.team-heading')).toContainText('Photon Pigeons')
  await a.screenshot({ path: testInfo.outputPath('questions-desktop.png'), fullPage: true })
  await a.getByRole('link', { name: 'Game', exact: true }).click(); await c.getByRole('link', { name: 'Game', exact: true }).click(); await b.getByRole('link', { name: 'Game', exact: true }).click()
  // Two teams: four grounds. Orders are free until a boat fishes, and are public.
  await expect(a.getByRole('article', { name: 'Ground D' })).toBeVisible()
  await expect(a.getByRole('article', { name: 'Ground E' })).toHaveCount(0)
  await expect(a.getByText('No resolution yet', { exact: true })).toBeVisible()
  await a.getByRole('article', { name: 'Ground B' }).getByRole('button', { name: 'Send boat 1 here' }).click()
  await expect(a.getByRole('button', { name: /Boat 1.*Heading to B/ })).toBeVisible()
  await expect(a.locator('.research')).toContainText('30')
  await expect(c.getByRole('article', { name: 'Ground B' }).getByRole('listitem')).toHaveText(/→PP1.*Photon Pigeons, Boat 1, arriving/)
  // The teammate's device follows and can order the other boat.
  await expect(b.getByRole('button', { name: /Boat 1.*Heading to B/ })).toBeVisible()
  await b.getByRole('button', { name: /Boat 2/ }).click()
  await b.getByRole('article', { name: 'Ground C' }).getByRole('button', { name: 'Send boat 2 here' }).click()
  await expect(a.getByRole('button', { name: /Boat 2.*Heading to C/ })).toBeVisible()
  await a.getByRole('button', { name: 'Keep boat 1 idle' }).click()
  await expect(c.getByRole('article', { name: 'Ground B' }).getByRole('listitem')).toHaveCount(0)
  const groundA = (p: Page) => p.getByRole('listitem').filter({ hasText: 'Catch 12 fish at ground A.' })
  await groundA(a).getByRole('button', { name: 'Take' }).click()
  await expect(groundA(a)).toContainText('0 / 12')
  await expect(groundA(c)).toContainText('Photon Pigeons')
  await expect(b.getByRole('button', { name: 'Take' }).first()).toBeDisabled()
  await b.getByRole('button', { name: 'Abandon', exact: true }).click(); await b.getByRole('button', { name: 'Yes, abandon' }).click()
  await expect(a.getByRole('button', { name: 'Abandon', exact: true })).toHaveCount(0)
  await expect(groundA(c)).not.toContainText('Photon Pigeons')
  await a.screenshot({ path: testInfo.outputPath('game-desktop.png'), fullPage: true })
  await c.getByRole('link', { name: 'Standings', exact: true }).click()
  await expect(c.getByRole('region', { name: 'Scores' }).getByRole('row', { name: /Photon Pigeons/ }).getByRole('cell').last()).toHaveText('0')
  await a.getByRole('link', { name: 'Questions', exact: true }).click(); await expect(a.getByRole('heading', { level: 1 })).toHaveText(bank.physics['11–13'][1].prompt)
  await a.setViewportSize({ width: 390, height: 844 }); await a.screenshot({ path: testInfo.outputPath('questions-mobile.png'), fullPage: true })
  expect(await a.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await a.getByRole('button', { name: 'Skip question', exact: true }).scrollIntoViewIfNeeded(); expect(await a.locator('.research').evaluate(el => el.getBoundingClientRect().top)).toBeGreaterThanOrEqual(0); await a.getByRole('button', { name: 'Skip question', exact: true }).click(); await a.getByRole('button', { name: 'Yes, skip' }).click(); await expect(a.getByText('4 team skips left')).toBeVisible()
  await a.getByRole('link', { name: 'Game', exact: true }).click(); await a.screenshot({ path: testInfo.outputPath('game-mobile.png'), fullPage: true }); expect(await a.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await expect(page.getByRole('row', { name: /Photon Pigeons/ }).getByRole('cell').nth(2)).toHaveText('30')
  await expect(page.getByRole('row', { name: /Photon Pigeons/ }).getByRole('cell').nth(3)).toHaveText('0')
  await page.screenshot({ path: testInfo.outputPath('admin.png'), fullPage: true })
  await a.getByRole('link', { name: 'Standings', exact: true }).click()
  await expect(a.getByRole('heading', { name: 'Standings', exact: true })).toBeVisible()
  await expect(a.getByRole('region', { name: 'Scores' }).getByRole('row', { name: /Photon Pigeons/ }).getByRole('cell').last()).toHaveText('0')
  await a.screenshot({ path: testInfo.outputPath('standings-mobile.png'), fullPage: true })
  expect(await a.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await a.reload(); await expect(a.getByRole('timer')).toHaveText(/44:[0-5][0-9]/)
  await a.getByRole('link', { name: 'Questions', exact: true }).click()
  await contextA.route('**/api/team/state', async route => {
    const response = await route.fetch(), body = await response.json()
    body.standings.frozenAt = Date.now()
    // A recorded resolution, so the summary for a returning player can be checked.
    const rival = body.game.teams.find((team: { id: string }) => team.id !== body.team.id).id
    body.game.resolution = 3
    body.game.last = { number: 3, at: Date.now(), grounds: [], own: { id: body.team.id, paid: 1, caught: 2, research: 29, fish: 2, bonus: 0, contract: { id: 'ground-a', progress: 2, target: 12, completed: false },
      boats: [{ from: 'B', order: 'B', to: 'B', action: 'fish', caught: 2 }, { from: null, order: 'C', to: 'C', action: 'travel', caught: 0 }] },
      teams: [{ id: rival, caught: null, boats: [{ from: 'A', order: 'A', to: 'A', action: 'fish', caught: null }, { from: null, order: null, to: null, action: 'idle', caught: null }] }] }
    await route.fulfill({ response, json: body })
  })
  await a.getByRole('link', { name: 'Game', exact: true }).click()
  await expect(a.getByRole('heading', { name: 'Resolution 3', exact: true })).toBeVisible()
  await expect(a.getByText('Boat 1: caught 2 fish at B', { exact: true })).toBeVisible()
  await expect(a.getByText('Boat 2: travelled to C', { exact: true })).toBeVisible()
  await expect(a.getByText('Contract progress 2 / 12', { exact: true })).toBeVisible()
  await expect(a.getByText('Rival catches are hidden while standings are frozen.', { exact: true })).toBeVisible()
  await a.getByRole('link', { name: 'Standings', exact: true }).click()
  await expect(a.getByText('Frozen for the final 5 minutes.', { exact: true })).toBeVisible()
  await a.reload()
  await expect(a.getByText('Frozen for the final 5 minutes.', { exact: true })).toBeVisible()
  await contextA.unroute('**/api/team/state')
  // An authoritative expiry response should immediately replace either view.
  await contextA.route('**/api/**', async route => {
    const path = new URL(route.request().url()).pathname
    if (!['/api/competition', '/api/team/state'].includes(path)) return route.continue()
    const response = await route.fetch(), body = await response.json()
    const clock = path === '/api/competition' ? body : body.competition
    clock.status = 'finished'; clock.endsAt = clock.serverNow - 1
    await route.fulfill({ response, json: body })
  })
  await expect(a.getByRole('heading', { level: 1 })).toHaveText('Competition over.')
  await expect(a.getByRole('region', { name: 'Scores' })).toHaveCount(0)
  await expect(a.getByRole('timer')).toHaveText('00:00')
  await expect(a.getByRole('button', { name: 'Submit answer' })).toHaveCount(0)
  await a.getByRole('link', { name: 'Game', exact: true }).click()
  await expect(a.getByRole('region', { name: 'Fishing grounds' })).toHaveCount(0)
  await expect(a.getByRole('button', { name: 'Take', exact: true })).toHaveCount(0)
  await a.getByRole('link', { name: 'Standings', exact: true }).click()
  await expect(a.getByRole('heading', { level: 1 })).toHaveText('Competition over.')
  await expect(a.getByRole('region', { name: 'Scores' })).toHaveCount(0)
  expect(pageErrors).toEqual([])
  await contextA.close(); await contextB.close(); await contextC.close()
})
test('invalid code and offline failures are understandable', async ({ page }) => {
  await page.goto('/'); await page.getByLabel('Team code').fill('ZZZZ'); await page.getByRole('button', { name: 'Join', exact: true }).click(); await expect(page.getByRole('alert')).toContainText('That code was not found')
  await page.route('**/api/team/login', route => route.abort()); await page.getByRole('button', { name: 'Join', exact: true }).click(); await expect(page.getByRole('alert')).toContainText('Cannot reach the server')
})

test('Czech UI and grading share progress without changing drafts or attempts', async ({ browser, page }, testInfo) => {
  const headers = { 'X-Competition-Client': '1' }
  await page.request.post('/api/admin/login', { headers, data: { password: 'browser-test-password' } })
  await page.request.post('/api/admin/teams', { headers, data: { name: 'Czech team', age: '11–13', code: 'CZ11' } })
  const competition = await (await page.request.get('/api/competition')).json()
  if (competition.status === 'waiting') await page.request.post('/api/admin/start', { headers, data: {} })
  const otherContext = await browser.newContext()
  const other = await otherContext.newPage()
  await join(other, 'CZ11')
  await page.goto('/')
  await page.getByLabel('Language / Jazyk').selectOption('cs')
  await expect(page.locator('html')).toHaveAttribute('lang', 'cs')
  await page.getByLabel('Kód týmu').fill('CZ11')
  await page.getByRole('button', { name: 'Připojit se', exact: true }).click()
  const first = bank.physics['11–13'][0]
  expect(first.type).toBe('multiple-choice')
  if (first.type !== 'multiple-choice') throw new Error('Expected MC fixture')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText(first.cs.prompt)
  await page.locator('.choice').nth(first.correctIndex).click()
  await page.getByLabel('Language / Jazyk').selectOption('en')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText(first.prompt)
  await expect(page.getByRole('radio').nth(first.correctIndex)).toBeChecked()
  await page.getByLabel('Language / Jazyk').selectOption('cs')
  await expect(page.getByRole('radio').nth(first.correctIndex)).toBeChecked()
  const unchanged = await (await page.request.get('/api/team/state')).json()
  expect(unchanged.progress.physics.attempts).toBe(0)
  expect(unchanged.team.research).toBe(0)
  await page.getByRole('button', { name: 'Odeslat odpověď' }).click()
  await expect(page.getByRole('status')).toContainText('Správně · +10 Výzkum')
  await expect(other.getByRole('heading', { level: 1 })).toHaveText(bank.physics['11–13'][1].prompt)
  await expect(other.getByLabel('Language / Jazyk')).toHaveValue('en')
  await expect(other.locator('.research')).toContainText('10 Research')
  await page.getByRole('button', { name: 'Biologie', exact: true }).click()
  const bio = bank.biology['11–13'][0]
  if (bio.type !== 'multiple-choice') throw new Error('Expected MC fixture')
  await page.locator('.choice').nth(bio.correctIndex).click()
  await page.getByRole('button', { name: 'Odeslat odpověď' }).click()
  await page.getByLabel('Vaše odpověď').fill('60,0')
  await page.getByLabel('Language / Jazyk').selectOption('en')
  await expect(page.getByLabel('Your answer')).toHaveValue('60,0')
  await page.getByLabel('Language / Jazyk').selectOption('cs')
  await page.getByRole('button', { name: 'Odeslat odpověď' }).click()
  await expect(page.getByRole('status')).toContainText('Správně · +10 Výzkum')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText(bank.biology['11–13'][2].cs.prompt)
  await chooseCorrect(other, 'physics', 1)
  await other.getByRole('button', { name: 'Submit answer' }).click()
  await page.getByRole('button', { name: 'Fyzika', exact: true }).click()
  await expect(page.getByRole('heading', { level: 1 })).toHaveText(bank.physics['11–13'][2].cs.prompt)
  await page.getByLabel('Vaše odpověď').fill('5,0')
  await page.getByRole('button', { name: 'Odeslat odpověď' }).click()
  await expect(page.getByRole('status')).toContainText('Správně · +10 Výzkum')
  await page.reload()
  await expect(page.getByLabel('Language / Jazyk')).toHaveValue('cs')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText(bank.physics['11–13'][3].cs.prompt)
  await page.getByLabel('Vaše odpověď').fill('  dolů  ')
  await page.getByRole('button', { name: 'Odeslat odpověď' }).click()
  await expect(page.locator('.research')).toContainText('60 Výzkum')
  await expect(other.locator('.research')).toContainText('60 Research')
  // Czech scientific text and code output both work, even after switching UI language.
  const csTrack = bank['computer-science']['11–13']
  const textIndex = csTrack.findIndex(q => q.id === 'computer-science-11-09')
  expect(textIndex).toBeGreaterThanOrEqual(0)
  for (const q of csTrack.slice(0, textIndex)) {
    const answer = q.type === 'multiple-choice' ? String(q.correctIndex) : q.type === 'numerical' ? String(q.numericAnswer) : q.acceptedAnswers[0]
    const response = await page.request.post('/api/team/answer', { headers, data: { subject: 'computer-science', questionId: q.id, answer } })
    expect(response.ok()).toBe(true)
  }
  await page.getByRole('button', { name: 'Informatika', exact: true }).click()
  await expect(page.getByRole('heading', { level: 1 })).toHaveText(csTrack[textIndex].cs.prompt)
  await page.getByLabel('Vaše odpověď').fill('  ne  ')
  await page.getByLabel('Language / Jazyk').selectOption('en')
  await expect(page.getByLabel('Your answer')).toHaveValue('  ne  ')
  await page.getByRole('button', { name: 'Submit answer' }).click()
  await expect(page.getByRole('status')).toContainText('Correct · +10 Research')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText(csTrack[textIndex + 1].prompt)
  await page.getByLabel('Language / Jazyk').selectOption('cs')
  await expect(other.locator('.research')).toContainText('160 Research')
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('czech-questions-mobile.png'), fullPage: true })
  await page.getByRole('link', { name: 'Hra', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Vaše lodě' })).toBeVisible()
  await expect(page.getByText('Ulovte 12 ryb na lovišti A.', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Pořadí', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Pořadí' })).toBeVisible()
  await page.goto('/admin')
  await expect(page.getByRole('heading', { name: 'Týmy', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Přidat tým' })).toBeVisible()
  await otherContext.close()
})
